services:
  redis:
    image: redis:7.2-alpine
    networks:
      - simtrade-network

  timescaledb:
    image: rumike207/simtrade-timescaledb:latest 
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB="${DATABASE_DB:-simtrade_db}"
      - POSTGRES_USER=${DATABASE_USERNAME:-XXXXXX}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-XXXXXX}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "XXXXXX", "-d", "simtrade_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    networks:
      - simtrade-network

  user-service:
    image: rumike207/simtrade-user-service:latest 
    depends_on:
      timescaledb:
        condition: service_healthy
      redis:
        condition: service_started
      kafka:
        condition: service_started
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=false # Disable devtools for deployed image
      - SPRING_DATASOURCE_URL=jdbc:postgresql://timescaledb:5432/simtrade_db
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME:-XXXXXX}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD:-XXXXXX}
      - JWT_SECRET=XXXXXX==
      - JWT_EXPIRATION=864000000
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CONSUMER_GROUP_ID=leaderboard-group
      - KAFKA_CONSUMER_AUTO_OFFSET_RESET=latest
      - LOGGING_LEVEL_COM_SIMTRADE_USER_SERVICE=INFO
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=INFO
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=INFO
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_KAFKA=INFO
      - LOGGING_LEVEL_ORG_APACHE_KAFKA=INFO
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_DATA_REDIS=INFO
      - MARKET_SERVICE_URL=http://market-service:8080
      - USER_SERVICE_URL=http://user-service:8080
      - ORDER_SERVICE_URL=http://order-service:8080
    networks:
      - simtrade-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 1
    networks:
      - simtrade-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ["CMD", "zookeeper-shell", "zookeeper:2181", "ls", "/"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - simtrade-network

  order-service:
    image: rumike207/simtrade-order-service:latest 
    depends_on:
      timescaledb:
        condition: service_healthy
      redis:
        condition: service_started
      kafka:
        condition: service_started
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=false
      - SPRING_DATASOURCE_URL=jdbc:postgresql://timescaledb:5432/simtrade_db
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME:-XXXXXX}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD:-XXXXXX}
      - JWT_SECRET=XXXXXX==
      - JWT_EXPIRATION=864000000
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CONSUMER_GROUP_ID=leaderboard-group
      - KAFKA_CONSUMER_AUTO_OFFSET_RESET=latest
      - LOGGING_LEVEL_COM_SIMTRADE_USER_SERVICE=INFO
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=INFO
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=INFO
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_KAFKA=INFO
      - LOGGING_LEVEL_ORG_APACHE_KAFKA=INFO
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_DATA_REDIS=INFO
      - MARKET_SERVICE_URL=http://market-service:8080
      - USER_SERVICE_URL=http://user-service:8080
      - ORDER_SERVICE_URL=http://order-service:8080
    networks:
      - simtrade-network

  market-service:
    image: rumike207/simtrade-market-service:latest 
    depends_on:
      timescaledb:
        condition: service_healthy
      redis:
        condition: service_started
      kafka:
        condition: service_started
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=false
      - SPRING_DATASOURCE_URL=jdbc:postgresql://timescaledb:5432/simtrade_db
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME:-XXXXXX}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD:-XXXXXX}
      - SERVER_PORT=8080
      - JWT_SECRET=XXXXXX
      - JWT_EXPIRATION=864000000
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CONSUMER_GROUP_ID=leaderboard-group
      - KAFKA_CONSUMER_AUTO_OFFSET_RESET=latest
      - LOGGING_LEVEL_COM_SIMTRADE_USER_SERVICE=INFO
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=INFO
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=INFO
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_KAFKA=INFO
      - LOGGING_LEVEL_ORG_APACHE_KAFKA=INFO
      - MARKET_SERVICE_URL=http://market-service:8080
      - USER_SERVICE_URL=http://user-service:8080
      - ORDER_SERVICE_URL=http://order-service:8080
    networks:
      - simtrade-network

  # Laravel Portfolio Application
  laravel:
    image: rumike207/simtrade-laravel:latest 
    networks:
      - simtrade-network

  # NGINX Gateway
  gateway:
    image: rumike207/simtrade-gateway:latest 
    ports:
      - "${GATEWAY_PORT:-80}:8080"
    depends_on:
      - user-service
      - market-service
      - order-service
      - laravel
    networks:
      - simtrade-network

networks:
  simtrade-network:
    driver: bridge

volumes:
  timescaledb_data:
